name: globbing
version: 0.0.3
author: Andrew Mezoni <andrew.mezoni@gmail.com>
description: Globbing is a library for fast directory listing based on the wildcard patterns.
homepage: https://github.com/mezoni/globbing
dependencies:
  ascii: any
  lists: any
dev_dependencies:
  path: any
  unittest: any
