name: globbing
version: 0.1.15
author: Andrew Mezoni <andrew.mezoni@gmail.com>
description: Globbing is a library for pattern matching based on wildcard characters.
homepage: https://github.com/mezoni/globbing
dev_dependencies:
  path: any
  unittest: any
