name: globbing
version: 0.1.5
author: Andrew Mezoni <andrew.mezoni@gmail.com>
description: Globbing is a library for fast directory listing based on the wildcard patterns. Uses an intelligent search operations with reduced amount of operations of disk access.
homepage: https://github.com/mezoni/globbing
dev_dependencies:
  path: any
  unittest: any
